// chat-data.js
const CHAT_DATA = [
  {"username": "NightOwl", "message": "Anyone still awake or are we all pretending to sleep again? 😂"},
  {"username": "VelvetVibe", "message": "Still up. Scrolling through memes like it's a full-time job."},
  {"username": "ChillFox", "message": "Same. Can't sleep. Too much caffeine or too many thoughts?"},
  {"username": "UrbanMuse", "message": "Probably both. Welcome to insomnia o'clock."},
  {"username": "ClubKing", "message": "Lmao I just got home. The DJ actually played 'Mr. Brightside' again."},
  {"username": "VelvetVibe", "message": "Classic. Every night ends with that song and drunk people screaming the lyrics."},
  {"username": "NightOwl", "message": "It’s basically the national anthem of chaos."},
  {"username": "GossipGuru", "message": "Haha true. Also hi everyone 😏"},
  {"username": "ChillFox", "message": "Hey Guru, how was your night? You look alive enough to type."},
  {"username": "GossipGuru", "message": "Barely. My feet hate me. Why are heels even legal?"},
  {"username": "UrbanMuse", "message": "For the aesthetic. Pain is fashion’s favorite side dish."},
  {"username": "VelvetVibe", "message": "Muse wins quote of the night 😂"},
  {"username": "LateLatte", "message": "hi"},
  {"username": "NightOwl", "message": "Hey LateLatte ☕ welcome to the chaos!"},
  {"username": "ClubKing", "message": "Muse always talks like she’s narrating a perfume ad."},
  {"username": "UrbanMuse", "message": "I contain multitudes, babe."},
  {"username": "VelvetVibe", "message": "You contain drama and caffeine, mostly."},
  {"username": "NightOwl", "message": "And an alarming number of mysterious quotes."},
  {"username": "GossipGuru", "message": "Okay but who saw the guy dancing on the table tonight? Iconic."},
  {"username": "ClubKing", "message": "Oh god, that was my friend Max. I told him tequila isn’t water."},
  {"username": "VelvetVibe", "message": "It’s hydration for the soul."},
  {"username": "ChillFox", "message": "That’s not how bodies work 😂"},
  {"username": "UrbanMuse", "message": "But that *is* how Saturday nights work."},
  {"username": "NightOwl", "message": "Speaking of, who’s ready for brunch tomorrow?"},
  {"username": "GossipGuru", "message": "If by brunch you mean therapy with mimosas, count me in."},
  {"username": "VelvetVibe", "message": "That’s the only kind of brunch I acknowledge."},
  {"username": "PartyGhost", "message": "hi"},
  {"username": "ChillFox", "message": "Hey PartyGhost 👋 welcome!"},
  {"username": "ClubKing", "message": "We’re the friend group that never logs off."},
  {"username": "UrbanMuse", "message": "And somehow never runs out of sarcasm."},
  {"username": "NightOwl", "message": "Sarcasm is our love language."},
  {"username": "VelvetVibe", "message": "That and group selfies no one ever posts."},
  {"username": "GossipGuru", "message": "I have like 200 in drafts. I can’t pick one where we all look good."},
  {"username": "ChillFox", "message": "That’s impossible. Someone always blinks or eats air."},
  {"username": "NightOwl", "message": "Or makes that 'mid-laugh' face that ruins everything."},
  {"username": "VelvetVibe", "message": "I’m guilty of that. Every. Time."},
  {"username": "ClubKing", "message": "At least it’s authentic 😂"},
  {"username": "UrbanMuse", "message": "Authenticity is the new filter."},
  {"username": "GossipGuru", "message": "You should put that on a tote bag."},
  {"username": "SunnySip", "message": "hi"},
  {"username": "VelvetVibe", "message": "Hey Sunny! ☀️ grab a seat, grab a vibe."},
  {"username": "NightOwl", "message": "Okay but real talk — what’s everyone’s toxic trait tonight?"},
  {"username": "ChillFox", "message": "Mine’s thinking one more episode won’t hurt at 3 AM."},
  {"username": "UrbanMuse", "message": "Mine’s pretending I’m fine while stress-eating chips."},
  {"username": "VelvetVibe", "message": "Mine’s texting back ‘haha’ instead of dealing with my emotions."},
  {"username": "ClubKing", "message": "Mine’s agreeing to brunch knowing I’ll cancel."},
  {"username": "GossipGuru", "message": "Mine’s gossiping as self-care."},
  {"username": "NightOwl", "message": "At least you’re self-aware."},
  {"username": "DreamDrip", "message": "hi"},
  {"username": "ChillFox", "message": "Hey DreamDrip, welcome to our support group 😂"},
  {"username": "VelvetVibe", "message": "We accept all insomniacs and drama enthusiasts."},
  {"username": "UrbanMuse", "message": "Especially if you bring snacks."},
  {"username": "ClubKing", "message": "Speaking of snacks, I just ate leftover pizza and regret nothing."},
  {"username": "NightOwl", "message": "Pizza is self-love in triangle form."},
  {"username": "GossipGuru", "message": "It’s also my only consistent relationship."},
  {"username": "VelvetVibe", "message": "Mood."},
  {"username": "UrbanMuse", "message": "At least pizza doesn’t ghost you."},
  {"username": "ClubKing", "message": "Unless you forget it in the oven."},
  {"username": "ChillFox", "message": "Tragic love story right there."},
  {"username": "VelvetVibe", "message": "Okay but who’s actually showing up for brunch?"},
  {"username": "NightOwl", "message": "I’ll be there if my hangover allows."},
  {"username": "UrbanMuse", "message": "Same. I’ll bring sunglasses and silent judgment."},
  {"username": "GossipGuru", "message": "I’ll bring gossip and forgiveness."},
  {"username": "ClubKing", "message": "I’ll bring chaos."},
  {"username": "ChillFox", "message": "Perfect, full set assembled."},
  {"username": "RainyMood", "message": "hi"},
  {"username": "VelvetVibe", "message": "Hey RainyMood ☔ pull up a chair!"},
  {"username": "NightOwl", "message": "Muse, drop your skincare routine. You glowed tonight like a streetlamp."},
  {"username": "UrbanMuse", "message": "It’s just good lighting and emotional damage."},
  {"username": "ClubKing", "message": "Put that on your perfume ad 😂"},
  {"username": "GossipGuru", "message": "‘Emotional Damage’ — by Muse."},
  {"username": "VelvetVibe", "message": "With top notes of chaos and regret."},
  {"username": "ChillFox", "message": "10/10 would buy."},
  {"username": "NightOwl", "message": "We need to make fake ad campaigns, for real."},
  {"username": "UrbanMuse", "message": "Let’s make one called ‘Almost Functional’ — for adults trying their best."},
  {"username": "GossipGuru", "message": "Stop giving me business ideas at 2 AM 😭"},
  {"username": "VelvetVibe", "message": "You say that but you’ve got a notes app full of them."},
  {"username": "ClubKing", "message": "This chat is basically a brainstorm for chaos."},
  {"username": "ChillFox", "message": "And friendship. Don’t forget friendship 😌"},
  {"username": "NightOwl", "message": "Aww, Fox getting sentimental again."},
  {"username": "VelvetVibe", "message": "It’s cute though. Balance out the sarcasm with some heart."},
  {"username": "UrbanMuse", "message": "Fine. I’ll allow it."},
  {"username": "ClubKing", "message": "Fox is our emotional support human."},
  {"username": "GossipGuru", "message": "True. The rest of us are just gremlins with Wi-Fi."},
  {"username": "VelvetVibe", "message": "Speak for yourself, I’m a glamorous gremlin."},
  {"username": "NightOwl", "message": "Same. Glittery chaos only."},
  {"username": "UrbanMuse", "message": "I prefer ‘artsy disaster.’"},
  {"username": "ClubKing", "message": "Mine’s just disaster, no art."},
  {"username": "ChillFox", "message": "Relatable content right there."},
  {"username": "SunnySip", "message": "hi"},
  {"username": "GossipGuru", "message": "Hey Sunny! You’re back 😄"},
  {"username": "VelvetVibe", "message": "This chat is starting to feel like an open mic night."},
  {"username": "NightOwl", "message": "Except everyone’s performing existential comedy."},
  {"username": "UrbanMuse", "message": "The only kind of comedy that hits after midnight."},
  {"username": "ClubKing", "message": "Anyone else still hungry or just me?"},
  {"username": "ChillFox", "message": "Always. Midnight hunger is my spirit animal."},
  {"username": "VelvetVibe", "message": "Fridge says no, but my heart says yes."},
  {"username": "NightOwl", "message": "That’s poetry."},
  {"username": "UrbanMuse", "message": "I feel like we should publish our midnight thoughts."},
  {"username": "GossipGuru", "message": "Call it ‘Messages We Shouldn’t Have Sent.’"},
  {"username": "ClubKing", "message": "Instant bestseller."},
  {"username": "LateLatte", "message": "hi"},
  {"username": "NightOwl", "message": "Hey LateLatte, back again? ☕"},
  {"username": "VelvetVibe", "message": "Loyal member of the chaos club."},
  {"username": "UrbanMuse", "message": "We should make loyalty cards at this point."},
  {"username": "ChillFox", "message": "Collect 10 nights, get one free nap."},
  {"username": "GossipGuru", "message": "I’d never earn it. Sleep and I broke up years ago."},
  {"username": "ClubKing", "message": "You two were toxic anyway."},
  {"username": "VelvetVibe", "message": "Same energy as ‘It’s not me, it’s the alarm clock.’"},
  {"username": "NightOwl", "message": "That one hurt a little 😂"},
  {"username": "UrbanMuse", "message": "I live off pain and playlists."},
  {"username": "DreamDrip", "message": "hi"},
  {"username": "ChillFox", "message": "Hey DreamDrip, you found us again 😎"},
  {"username": "GossipGuru", "message": "We need a bouncer for this chat. Too many mysterious intros."},
  {"username": "VelvetVibe", "message": "Nah, it’s fun. Every ‘hi’ feels like a jump scare."},
  {"username": "NightOwl", "message": "We’re the friendliest horror movie cast ever."},
  {"username": "ClubKing", "message": "Someone cue the dramatic music."},
  {"username": "UrbanMuse", "message": "Starring caffeine, chaos, and collective denial."},
  {"username": "VelvetVibe", "message": "Honestly, that sums us up."},
  {"username": "NightOwl", "message": "Group name locked in."},
  {"username": "RainyMood", "message": "hi"},
  {"username": "VelvetVibe", "message": "Hey Rainy! You’ve got perfect timing 🌧️"},
  {"username": "ClubKing", "message": "Rainy always joins during dramatic moments 😂"},
  {"username": "GossipGuru", "message": "The weather responds to our mood swings."},
  {"username": "UrbanMuse", "message": "Art imitates chat life."},
  {"username": "ChillFox", "message": "Or chat life imitates art."},
  {"username": "NightOwl", "message": "Either way, I’m ordering fries."},
  {"username": "VelvetVibe", "message": "Get extra sauce. We’re not animals."},
  {"username": "ClubKing", "message": "Speak for yourself."},
  {"username": "UrbanMuse", "message": "You *did* eat pizza off the counter earlier."},
  {"username": "ClubKing", "message": "5-second rule 😌"},
  {"username": "GossipGuru", "message": "That was a solid 30 seconds, bro."},
  {"username": "VelvetVibe", "message": "We all saw it happen."},
  {"username": "NightOwl", "message": "Legends never die, they just risk food poisoning."},
  {"username": "UrbanMuse", "message": "Add that to our midnight quote book."},
  {"username": "ChillFox", "message": "We’re unintentionally philosophical."},
  {"username": "ClubKing", "message": "That’s the best kind of philosophical."},
  {"username": "VelvetVibe", "message": "Okay but why do all our convos sound like indie movie scripts?"},
  {"username": "NightOwl", "message": "Because we’re the main characters of our insomnia arc."},
  {"username": "UrbanMuse", "message": "Directed by chaos, written by caffeine."},
  {"username": "GossipGuru", "message": "And edited by regret."},
  {"username": "ChillFox", "message": "I’d watch that movie."},
  {"username": "ClubKing", "message": "You *are* that movie."},
  {"username": "VelvetVibe", "message": "Touché."},
  {"username": "NightOwl", "message": "Okay, serious question: does anyone ever finish a series or do we all just restart old ones?"},
  {"username": "UrbanMuse", "message": "I rewatch comfort shows like they pay me."},
  {"username": "VelvetVibe", "message": "Same. I’m emotionally attached to fictional characters more than real people."},
  {"username": "GossipGuru", "message": "At least they don’t leave you on read."},
  {"username": "ChillFox", "message": "Can’t leave if they never reply."},
  {"username": "ClubKing", "message": "Deep. Pass the fries."}
];
